# Generated by Django 3.0.1 on 2022-02-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intuit',
            fields=[
                ('player_id', models.CharField(max_length=1500, primary_key=True, serialize=False)),
                ('birth_country', models.CharField(blank=True, default=False, max_length=1500)),
                ('birth_state', models.CharField(blank=True, default=False, max_length=1500)),
                ('birth_city', models.CharField(blank=True, default=False, max_length=1500)),
                ('birthYear', models.IntegerField(null=True)),
                ('birthMonth', models.IntegerField(null=True)),
                ('birthDay', models.IntegerField(null=True)),
                ('deathYear', models.IntegerField(null=True)),
                ('deathMonth', models.IntegerField(null=True)),
                ('deathDay', models.IntegerField(null=True)),
                ('deathCountry', models.CharField(blank=True, max_length=1500)),
                ('deathState', models.CharField(blank=True, max_length=1500)),
                ('deathCity', models.CharField(blank=True, max_length=1500)),
                ('nameFirst', models.CharField(blank=True, max_length=1500)),
                ('nameLast', models.CharField(blank=True, max_length=1500)),
                ('nameGiven', models.CharField(blank=True, max_length=1500)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bats', models.CharField(default=False, max_length=1500, null=True)),
                ('throws', models.CharField(blank=True, default=False, max_length=1500)),
                ('debut', models.DateTimeField(auto_now_add=True, null=True)),
                ('finalGame', models.DateTimeField(auto_now_add=True, null=True)),
                ('retroID', models.CharField(blank=True, default=False, max_length=1500)),
                ('bbrefID', models.CharField(blank=True, default=False, max_length=1500)),
            ],
        ),
    ]
